#!/bin/bash
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# This example catches duplicate Signed-off-by lines.
line_num=1
while read line
do	
	TYPE_MSG_PATTERN="^(Feat:|Docs:|Fix:|Refactor:|Perf:|Test:)[ ][\s\S]*"
	SUBJECT_MSG_PATTERN="^- "
	BLANKLINE_MSG_PATTERN="^$"
	CEMMENT_MSG_PATTERN="^#" 
	if [[ $line =~ $TYPE_MSG_PATTERN ]] && [[ $line_num != 1 ]]; then
		echo -e "\033[31mError: Only the first line can be commit type! \033[0m"
	fi
	let line_num++
	if [[ $line =~ $TYPE_MSG_PATTERN ]] || [[ $line =~ $BLANKLINE_MSG_PATTERN ]] || [[ $line =~ $SUBJECT_MSG_PATTERN ]] || [[ $line =~ $CEMMENT_MSG_PATTERN ]]; then
		continue
	else
		echo -e "\033[31mError: Commit Message! \033[0m"
		echo -e "\033[31mIrregular Commit Message: $line \033[0m"
		echo -e "\033[31mPlease obey robosense commit message rules: modify your CHANGELOG.MD, then copy reguler commit message! \033[0m"
		echo -e "\033[32mexample:
Feat: 一行总结性描述(必须的，注意冒号后面有空格)

- 说明1(可选的)
- 说明2(可选的)"
		exit 1
	fi
done < $1